# Travaux Pratique : Lights out

### Import

In [11]:
import numpy as np


## Exercice 1

### Question 1

### Question 2

In [12]:
def Vecteur_Colonne(A) :
    return np.reshape(A, (1, -1)) #reshape(A, (1, -1)) permet de réécrire la matrice A sur 1 ligne et autant de colonne que possible (le -1 permets ça)

In [13]:
#Exemple
#matrice = np.array([[1,2,3],[4,5,6]])
#print(Vecteur_Colonne(matrice))

### Question 3

In [14]:
def Matrice(V) :
    length = int(sqrt(len(V[0])))
    return np.reshape(V, (length, length))

In [15]:
#Exemple
#vecteur = np.array([1,2,3,4,5,6,7,8,9])
#print(Matrice(vecteur))

## Exercice 2

In [16]:
def Croix(i, j, n) :
    matrice = np.zeros((n, n))
    
    matrice[i][j] = 1
    if(i > 0) :
        matrice[i-1][j] = 1
    if(j > 0) :
        matrice[i][j-1] = 1
    if(i < n-1) :
        matrice[i+1][j] = 1
    if(j < n-1) :
        matrice[i][j+1] = 1
        
    return matrice

In [17]:
#Exemple
#print(Croix(2,3,5))

## Exercice 3

In [18]:
def InitJeu() :
    print("Bienvenue sur le jeu Lights Out !\n(© Loïck Gourvil)\n")
    x = 3
    matriceDeJeu = np.empty([x,x])
    for i in range(0, len(matriceDeJeu)) :
        for j in range(0, len(matriceDeJeu[i])) :
            matriceDeJeu[i][j] = np.random.randint(0,2)
            
    return matriceDeJeu

In [19]:
#Exemple
#matriceDeJeu = InitJeu()
#print(matriceDeJeu)

In [20]:
def TourJoueur() :
    #Récupération du numéro de ligne
    while True :
        print("Sur quelle ligne se trouve la case que vous souhaitez cliquer ? (première ligne = 0)")
        x = int(input())
        if(0 <= x < 3):
            break
        else:
            print("Valeure incorrecte, veuillez saisir une valeure comprise entre 0 et 3")
    
    #Récupération du numéro de colonne
    while True :
        print("Sur quelle colonne se trouve la case que vous souhaitez cliquer ? (première colonne = 0)")
        y = int(input())
        if(0 <= y < 3):
            break
        else:
            print("Valeure incorrecte, veuillez saisir une valeure comprise entre 0 et 3")
    return Croix(x, y, 3)

TourJoueur()

Sur quelle ligne se trouve la case que vous souhaitez cliquer ? (première ligne = 0)
Sur quelle colonne se trouve la case que vous souhaitez cliquer ? (première colonne = 0)


array([[1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [21]:
#Exemple
#matriceJouer = TourJoueur()
#print(matriceJouer)

In [22]:
def CalculNouvelleMatrice(matriceDeJeu, matriceJouer) :
    for i in range(0, len(matriceDeJeu)) :
        for j in range(0, len(matriceDeJeu[i])) :
            if(matriceJouer[i][j] == 1):
                if(matriceDeJeu[i][j] == 1):
                    matriceDeJeu[i][j] = 0
                else:
                    matriceDeJeu[i][j] = 1

    return matriceDeJeu

In [23]:
#Exemple
#matriceDeJeu = InitJeu()
#print(matriceDeJeu)
#matriceJouer = TourJoueur()
#print(matriceJouer)
#print("-------------")
#matriceDeJeu = CalculNouvelleMatrice(matriceDeJeu, matriceJouer)
#print(matriceDeJeu)

In [24]:
def Lights_out() :
    matriceDeJeu = InitJeu()
    
    while True :
        print("----------------")
        print("Matrice de jeu :")
        print(matriceDeJeu)
        matriceJouer = TourJoueur()
        matriceDeJeu = CalculNouvelleMatrice(matriceDeJeu, matriceJouer)
        
        if np.all(matriceDeJeu == 0):
            print("Vous avez gagner !")
            break

In [25]:
#Jeu
Lights_out()

Bienvenue sur le jeu Lights Out !
(© Loïck Gourvil)

----------------
Matrice de jeu :
[[1. 1. 0.]
 [0. 1. 0.]
 [1. 1. 0.]]
Sur quelle ligne se trouve la case que vous souhaitez cliquer ? (première ligne = 0)
Sur quelle colonne se trouve la case que vous souhaitez cliquer ? (première colonne = 0)
----------------
Matrice de jeu :
[[0. 0. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]
Sur quelle ligne se trouve la case que vous souhaitez cliquer ? (première ligne = 0)
Sur quelle colonne se trouve la case que vous souhaitez cliquer ? (première colonne = 0)
----------------
Matrice de jeu :
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
Sur quelle ligne se trouve la case que vous souhaitez cliquer ? (première ligne = 0)
Sur quelle colonne se trouve la case que vous souhaitez cliquer ? (première colonne = 0)


ValueError: invalid literal for int() with base 10: ''

## Exercice 4

In [26]:
def Matrice_Passage(n):
    matriceCroix = []
    
    for i in range(n):
        for j in range(n):
            matriceCroix.append(Vecteur_Colonne(Croix(i, j, n)))
    
    matricePassage = np.vstack(matriceCroix).T
    return matricePassage

In [ ]:
#Exemple
#print(Matrice_Passage(3))

## Exercice 5

### Question 1

In [ ]:
for n in range(2, 12):
    matricePassage = Matrice_Passage(n)
    determinant = int(np.linalg.det(matricePassage).round() % 2)
    print("Pour n =",n," le déterminant est",determinant)

Pour n = 2  le déterminant est 1
Pour n = 3  le déterminant est 1
Pour n = 4  le déterminant est 0
Pour n = 5  le déterminant est 0
Pour n = 6  le déterminant est 1
Pour n = 7  le déterminant est 1
Pour n = 8  le déterminant est 1
Pour n = 9  le déterminant est 0
Pour n = 10  le déterminant est 1
Pour n = 11  le déterminant est 0


### Question 2

In [ ]:
for n in range(2, 12):
    matricePassage = Matrice_Passage(n)
    determinant = int(np.linalg.det(matricePassage).round() % 2)
    if determinant == 1:
        print("Pour n =",n,"il existe une solution unique")

Pour n = 2 il existe une solution unique
Pour n = 3 il existe une solution unique
Pour n = 6 il existe une solution unique
Pour n = 7 il existe une solution unique
Pour n = 8 il existe une solution unique
Pour n = 10 il existe une solution unique


## Exercice 6

In [ ]:
np.linalg.inv(Matrice_Passage(2)).round() % 2

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

## Exercice 7

In [ ]:
def Inverse(A):
    A = A.round(0)
    A = A.astype(int)
    
    matrice = Matrix(A)
    matriceInv = matrice.inv_mod(2)
    matriceInv = np.array(matriceInv)
    return matriceInv

In [ ]:
#Exemple
#A = Matrice_Passage(3)
#print(A)
#print(Inverse(A))

In [ ]:
def Solution(A):
    taille = int(sqrt(np.size(A)))
    vectA = A.reshape(taille**2, 1)
    matriceInv = Inverse(Matrice_Passage(3))
    
    # Calculer la solution S
    vectS = np.dot(matriceInv,vectA) % 2

    # Reconvertir la matrice colonne en une matrice taille*taille
    S = vectS.reshape(taille,taille)
    
    return S

In [ ]:
#Exemple
S = Solution(np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]]))
print(S)

[[0 0 0]
 [0 1 0]
 [0 0 0]]
